### ISSUE TITLE
导航链接点击报404

### ISSUE THREAD

**Issue by REDzhangyuxuan** [limijiaoyin/taikang#67]
![image](https://cloud.githubusercontent.com/assets/12409019/10121102/5419c21a-650f-11e5-8824-4ef32dabe907.png)
点击“清单详情”后报404

![image](https://cloud.githubusercontent.com/assets/12409019/10121100/484d8264-650f-11e5-8514-27eca1cd7f20.png)

**Comment by lucknessbuaa** [comment]
done
